### PR TITLE
Fix some errors in the barrier

### LINKED ISSUE #67: Barrier类修改
# 以下情况下不会抛出协程错误异常，正常执行

-  执行的任务中没有发生协程切换
-  执行任务列表为空，没有任务

# 修改后的类
```
use Swoole\Coroutine;
use Swoole\Exception;
use Swoole\Timer;

class Barrier
{
    private $cid = -1;

    private $timer = -1;

    private static $cancel_list = [];

    public function __destruct()
    {
        if ($this->timer != -1) {
            Timer::clear($this->timer);
            if (static::$cancel_list[$this->cid]) {
                unset(static::$cancel_list[$this->cid]);
                return;
            }
        }

        if ($this->cid != -1 && $this->cid != Coroutine::getCid()) {
            Coroutine::resume($this->cid);
        }else{
            self::$cancel_list[$this->cid] = true;
        }
    }

    public static function make()
    {
        return new static();
    }

    /**
     * @throws Exception
     */
    public static function wait(Barrier &$barrier, float $timeout = -1)
    {
        if ($barrier->cid != -1) {
            throw new Exception('The barrier is waiting, cannot wait again.');
        }
        $cid = Coroutine::getCid();
        $barrier->cid = $cid;
        if ($timeout > 0 && ($timeout_ms = intval($timeout * 1000)) > 0) {
            $barrier->timer = Timer::after($timeout_ms, function () use ($cid) {
                self::$cancel_list[$cid] = true;
                Coroutine::resume($cid);
            });
        }
        $barrier = null;
        (!(self::$cancel_list[$cid] ?? false)) && Coroutine::yield();
    }
}
```

### PR DESCRIPTION
**Pull request by sy-records**
close #67

```bash
PHP Notice:  Undefined offset: 1 in @swoole-src/library/core/Coroutine/Barrier.php on line 30

PHP Warning:  Swoole\Coroutine::resume(): you can not resume the coroutine which is in IO operation or non-existent in @swoole-src/library/core/Coroutine/Barrier.php on line 36
```

### CODE REVIEW

File: src/core/Coroutine/Barrier.php [hunk 1]
```diff
@@ -27,13 +27,15 @@ public function __destruct()
...
+            if (isset(static::$cancel_list[$this->cid])) {
                 unset(static::$cancel_list[$this->cid]);
                 return;
             }
         }
-        if ($this->cid != -1) {
+        if ($this->cid != -1 && $this->cid != Coroutine::getCid()) {
             Coroutine::resume($this->cid);
+        } else {
+            static::$cancel_list[$this->cid] = true;
```
Comment (deminy) [inline src/core/Coroutine/Barrier.php:38]: Line 38 should better be:

```php
            if (isset(static::$cancel_list[$this->cid])) {
                unset(static::$cancel_list[$this->cid]);
            }
```

**Review by deminy — APPROVED** [review]
The destructor method doesn't always clean up the array _self::$cancel_list_ properly. I will add more test cases afterwards.

File: src/core/Coroutine/Barrier.php (hunk 1 above)
Comment (sy-records) [reply src/core/Coroutine/Barrier.php:38]: I'm actually waiting for a review from @matyhtf before the merge. 😂

If we use this, then the current coroutine result will be lost, Can't output `int(4)
int(4)
`.

```php
run(function () {
    $barrier = Barrier::make();

    $count = 0;
    $N = 4;

    foreach (range(1, $N) as $i) {
        Coroutine::create(function () use ($barrier, &$count) {
//            Coroutine::sleep(0.5);
            $count++;
        });
    }
    Barrier::wait($barrier, 1);
    var_dump($count, $N);
});
```
